name: pixelwerk
favicon: null
layout_spectrum: 1
typography_spectrum: 0.40303
title: first steps with thegrid
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f2f2f2'
    - '#010511'
    - '#88888a'
    - '#acabb0'
    - '#4d6577'
  brandStrength: 1
  lightness: 0
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
