name: pixelwerk
favicon: null
layout_spectrum: 1
typography_spectrum: 0.40303
title: pixelwerk
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f2f2f2'
    - '#010511'
    - '#88888a'
    - '#acabb0'
    - '#4d6577'
  brandStrength: 0.6682949957903475
  lightness: 0.8609254811890423
  saturation: 0.7069188694003969
  rhythmicContrast: 0.75
purpose: []
